Create Task form
htmlacademy-yii/603391-task-force-1 pull request #19
Opened 2020-10-01 08:42 UTC by romanrurenko

2020-10-15 14:36 UTC, mihan007 requested changes
Роман, ты проделал отличную работу! Видно, что ты понимаешь материал и хорошо усваиваешь информацию. Подрихтуем немного и можно в релиз :)

2020-10-15 14:36 UTC, mihan007 commented on console/migrations/m200930_124207_update_table_task.php
> +        $sql = 'ALTER TABLE `task` MODIFY `expire` TIMESTAMP DEFAULT NULL;
Я предлагаю не использовать чистые sql запросы для модификации схемы БД. Это усложняет восприятие кода и привязывает нас к одной СУБД, что не есть хорошо. В моем опыте были случаи, когда мы переходили с MySQL на PostgreSQL и ничего не переписывали в миграциях, так как они были сделаны через функции изменения БД фреймворка. Поэтому тут лучше перейти на эти функции. Смотри https://www.yiiframework.com/doc/guide/2.0/en/db-migrations#add-column

2020-10-15 14:36 UTC, mihan007 commented on console/migrations/m200930_124207_update_table_task.php
> +        echo "m200930_124207_update_table_task cannot be reverted.\n";
Обратные миграции обязательно писать всегда в случаях, когда ты изменяешь схему БД. В этих случаях их легко написать. Если миграция меняет какие-то данные, то уже надо оценивать насколько сложно эти изменения откатить. Эти миграции нужны, чтобы ты и другие разработчики могли откатываться на предыдущие версии БД в случае проблем при разработке. Смотри https://www.yiiframework.com/doc/guide/2.0/en/db-migrations#drop-column

2020-10-15 14:36 UTC, mihan007 commented on console/migrations/m200930_124207_update_table_task.php
> +    /*
Мертвый код будем всегда удалять из программы. Он создает мешанину в коде и повышает когнитивную нагрузку.

2020-10-15 14:36 UTC, mihan007 commented on console/migrations/m201009_020105_update.php
> +class m201009_020105_update extends Migration
желательно в имени миграции вкратце писать, что она делает. если сложно придумать имя миграции, то это означает, что она делает много всего и лучше разбить ее на несколько

2020-10-15 14:36 UTC, mihan007 commented on console/migrations/m201009_020105_update.php
> +        $sql = 'ALTER TABLE `task` DROP FOREIGN KEY `FK_task_status`;
Опять же уходим на https://www.yiiframework.com/doc/guide/2.0/en/db-migrations

2020-10-15 14:36 UTC, mihan007 commented on console/migrations/m201009_020105_update.php
> +        echo "m201009_020105_update cannot be reverted.\n";
Пишем обратную миграцию

2020-10-15 14:36 UTC, mihan007 commented on console/migrations/m201009_020105_update.php
> +    /*
Удаляем мертвый код

2020-10-15 14:36 UTC, mihan007 commented on frontend/assets/AppAsset.php
> +        //'yii\bootstrap\BootstrapAsset',
Убираем мертвый код

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/LandingController.php
> +        if (Yii::$app->user->getId()) {
1. Не увидел в ТЗ требования редиректа для залогиненного юзера https://up.htmlacademy.ru/yii/1/project/task-force#taskforce-6-1. Пусть на этой странице и остается

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/ResponseController.php
> +        $response = Response::findOne($id);
У нас много мест, где мы делаем поиск по id и если записи нет, то выкидываем 404 ошибку. Предлагаю уменьшить объем этого одинакового кода за счет использования специального trait, который эту всю проверку автоматом делает. Пример https://gist.github.com/mihan007/e151dee29eddb48e1ec045b83be47d33

Тогда 4 строчки мы заменим на $response = Response::findOrFail($id, "Отклик с ID #$id не найден");
Одна строка вместо 4х это очень хороший результат, так как и код уменьшился, и вероятность ошибки, и сам он выразительным стал. Дальше будет видно, что эта оптимизация может быть сделать в куче мест. Назовем ее findOrFail. На консультации разберем как она работает.

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/ResponseController.php
> +        $task->status = \TaskForce\Task::STATUS_IN_WORK;
Смотри какая тонкость. У нас есть диаграмма смены статусов и действий https://up.htmlacademy.ru/yii/1/project/task-force#taskforce-5-1. Поэтому, если строго следовать ТЗ, то при каждой попытке изменения статуса у задачи  и отклика надо проверить, а можем ли мы эту операцию смены статуса сделать. Есть разные способы это сделать, обсудим на консультации.

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/ResponseController.php
> +            throw new NotFoundHttpException("Не удалось назначить исполнителя отклика с ID #$id");
Эта строка генерирует ошибку 404. Эта ошибка по семантике http появляется, когда какая либо сущность не найдена. В нашем случае произошла ошибка работы с БД. Это серверная ошибка, ее http код 500 и для этой ошибки надо выбросить ServerErrorHttpException. Более того - ты выделил отдельно TaskForceException, давай его и кидать.

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/ResponseController.php
> +        $response = Response::findOne($id);
findOrFail

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/ResponseController.php
> +        $response->status = Response::STATUS_CANCELED;
проверить можем ли мы

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/ResponseController.php
> +
старайся перед return оставлять строго 1 пустую строку. это общепринятая нотация

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/SignupController.php
>      public function beforeAction($action)
В ТЗ ограничение по доступу к различным методам в зависимости от роли требуется сделать через ACF. https://up.htmlacademy.ru/yii/1/project/task-force#taskforce-3-3. https://www.yiiframework.com/doc/guide/2.0/en/security-authorization#access-control-filter

Будем разбираться как он работает.

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/SignupController.php
>          $this->enableCsrfValidation = false;
Отключение csrf валидации надо обосновать. Эта уязвимость опасная. Детали можешь узнать по https://habr.com/ru/company/acribia/blog/476880/

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/SignupController.php
>          if (Yii::$app->request->isPost) {
в коде лучше придерживаться одного стиля для одинаковых действий. Тут у тебя Yii::$app->request->isPost, а ранее я видел Yii::$app->request->getIsPost(). Да, эти две конструкции делают одно и тоже. Выбери одну и с ней дальше и иди по проекту.

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +
одна строка перед namespace. есть стандарт оформления кода PSR-12, https://www.php-fig.org/psr/psr-12/, в нем описаны эти ньюансы. В частности мое замечание https://stackoverflow.com/a/59892120/196893. 

Этот стандарт лучше соблюдать, чтобы при работе в команде(любой) ваш код выглядел единообразно. В PhpStorm можно включить автоматическое форматирование кода по этому стандарту, на консультации сделаем.

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +            throw new HttpException(self::HTTP_STATUS_403, 'Access denied.');
для этих случаев есть ForbiddenHttpException, лучше его использовать

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $role = Profile::findProfileByUserId($id)['role'];
Предлагаю избавиться от контроля доступа к методам внутри action. Это необходимо делать согласно тз используя ACF(https://www.yiiframework.com/doc/guide/2.0/en/security-authorization#access-control-filter).

Предлагаю тебе изучить тонкости в https://stackoverflow.com/a/31051259/196893 и создать два класса для предоставления доступа заказчику и исполнителю.

Например, это будут
1. class CustomerAccessRule extends \yii\filters\AccessRule
2. class ExecutorAccessRule extends \yii\filters\AccessRule

В каждом из них соответственно будет проверяться роль пользователя.

Это позволит тебе унести всю логику доступа к экшенам в behaviors и сделает код твоих экшенов намного меньше и выразительнее

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        if ($role !== \TaskForce\Task::ROLE_CUSTOMER) {
Подумай над тем, где должна находиться константа ROLE_CUSTOMER. Мне кажется, что роль относится больше к пользователю или его профилю чем к задаче

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +                return $this->render('create', compact('createTaskForm', 'categories'));
Попробуй поменять логику работы с $createTaskForm, чтобы $this->render('create'.. вызывался в функции один раз

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +            if ($taskID) {
А вот тут хорошо бы обработать случай, когда задача не создалась. Или упасть с ошибкой, или к форме добавить ошибку вида "Задача не создана, попробуйте позже"

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $currentUserRole = Profile::findProfileByUserId($currentUserId)['role'];
опять же это все уйдет после внедрения ACF

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $modelTask = Task::findTaskById($id);
Здесь снова уйдем к findOrFail https://gist.github.com/mihan007/e151dee29eddb48e1ec045b83be47d33

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $modelTask = Task::findTaskById($id);
Я вижу, что ты не смешиваешь модели ActiveRecord и модель бизнес логики. Это хорошо. Но лучше тогда вообще не работать в контроллере с ActiveRecord. Унеси всю работу с ней в \TaskForce\Task и работай только с ним из контроллера. А сейчас в одной функции и Task, и \TaskForce\Task - это несколько сводит с ума.

$task = \TaskForce\Task::findOrFail($id, "Задание с ID $id не найдено");
А уже внутри этого класса реализуй findOrFail, добавь private $model и в ней храни AR, если она нужна

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $task = new \TaskForce\Task(
Это всё уедет в класс Task, ты после выборки из базы просто сделаешь маппинг после AR на поля самого TaskForce\Task. То есть сделаешь инкапсуляцию. У тебя получится чистенький контроллер, все по красоте.

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        if ($currentUserId === (int)$taskOwnerId) {
Я бы эту логику тоже унес в Task. Ты выше отлично реализовал getAvailableActions, сделай по аналогии getAvailableResponses.
Вообще старайся по минимуму такую логику в контроллеры размещать, скорее всего она тебе понадобится и в других местах. Когда она в классе бизнес сущности, то ты ее просто переиспользуешь и не будешь заново писать

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $taskAssistUserId = ($currentUserId == $taskOwnerId && $taskExecutorId)
и это в Task

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $modelsFiles = File::findFilesByTaskID($id);
и это в Task

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        if ($taskAssistUserId) {
и это в Task

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $task = Task::findOne($id);
findOrFail

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        if (!$id) {
тут ошибка, должно быть !$task. Как раз за счет использования findOrFail ты от таких ошибок избавишься

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $role = Profile::findProfileByUserId($id)['role'];
Вообще у нас роль у конкретного пользователя и в Yii его правильно доставать через Yii::$app->user->identity->role

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $task = Task::findOne($id);
findOrFail

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $role = Profile::findProfileByUserId($id)['role'];
Yii::$app->user->identity->role

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $isAllow = RefuseAction::isAllowed(($taskId === $userId), $task->status, $role);
логику я бы перенес в класс Task. 

Будет что-то вроде 
if (!$task->isActionAllowedForUser(Task::ACTION_REFUSE, Yii::$app->user->identity)) {
    throw ForbiddenHttpException();
}

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $isAllow = RespondAction::isAllowed(($id === $userId), $task['status'], $role);
логику я бы перенес в класс Task. 

Будет что-то вроде 
if (!$task->isActionAllowedForUser(Task::ACTION_RESPOND, Yii::$app->user->identity)) {
    throw ForbiddenHttpException();
}

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $isAllow = CancelAction::isAllowed(($customerId === $userId), $task->status, $role);
логику я бы перенес в класс Task. 

Будет что-то вроде 
if (!$task->isActionAllowedForUser(Task::ACTION_CANCEL, Yii::$app->user->identity)) {
    throw ForbiddenHttpException();
}

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $task = Task::findOne($id);
findOrFail

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $task = Task::findOne($id);
findOrFail

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/TaskController.php
> +        $isAllow = CompleteAction::isAllowed(($task->customer_id === $userId), $task->status, $role);
логику я бы перенес в класс Task.
Будет что-то вроде if (!$task->isActionAllowedForUser(Task::ACTION_COMPLETE, Yii::$app->user->identity)) { throw ForbiddenHttpException(); }

2020-10-15 14:36 UTC, mihan007 commented on frontend/controllers/UsersController.php
>          $modelUser = Profile::findProfileByUserId($id);
ACF

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/CategoriesFilterForm.php
> +
не надо пустой строки

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/CompleteTaskForm.php
> +
не надо пустых строк

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/CreateTaskForm.php
> +    public function checkDate($attribute): void
неудачное название функции. непонятно, что проверяет checkDate. Может быть можно назвать так, чтобы было понятно, что мы проверяем, что $attribute в прошлом?

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/CreateTaskForm.php
> +        $isOldDate = strtotime('now') > strtotime($this->dateEnd);
Я понимаю, что мы проверяем $this->dateEnd в этой модели. Но все же стоит использовать тут $attribute, чтобы правило было универсальным и мы могли бы любую дату сюда передать

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/CreateTaskForm.php
> +    public function saveFields(int $id): ?int
попробуй переименовать аргумент функции, чтобы он обозначал то для чего он нужен

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/CreateTaskForm.php
> +            $file->saveAs($dirName . '/' . $file->name);
а что если у нас будут файлы с одинаковым именем? может добавим к имени файла что-нибудь, чтобы он стал уникальным?

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/CreateTaskForm.php
> +
пустая строка не нужна

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/ResponseTaskForm.php
> +
пустые строки не нужны

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/forms/ResponseTaskForm.php
> +    public $payment = '';
А для чего тут поля объявлены? Модель AR сама же их создаст

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/City.php
> +    public static function findAllCities(): array
попробуй проще назвать. ты же когда вызываешь, то пиешь City:: - то есть уже понятно, что функция будет работать для сущности City и в имени функции можно это не повторять

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/Profile.php
> +            ->asArray()->one();
так как тебе нужен ровно 1 элемент, то может и в sql добавим limit?

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/Response.php
> +
лишние пустые строки

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/Response.php
> +
лишние пустые строки

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/Specialization.php
>      public static function findSpecializationByUserId(int $userId)
подумай над названием функции. мы уже в контексте Specialization

2020-10-15 14:36 UTC, mihan007 commented on frontend/models/Task.php
> +            [['status'], 'string', 'max' => 20],
тут бы еще добавить валидатор, который проверяет, что status входит в список доступных статусов

2020-10-15 14:36 UTC, mihan007 commented on src/Task.php
> +        var_dump($currentUserId);
убрать дебаг

2020-10-15 14:36 UTC, mihan007 commented on src/Task.php
> +        if ($action::isAllowed($isOwner, $this->status, $role)) {
И все же логику isActionAllowed я бы перенес в Task, так как действие относится к ней. и скорее всего в какой-то момент потребуются ее поля. Например, нельзя будет взять задачу старше года. В текущей реализации ты везде в метод isAllowed начнешь передавать $task

2020-10-19 03:43 UTC, romanrurenko commented on frontend/controllers/LandingController.php
> +        if (Yii::$app->user->getId()) {
В ТЗ п. 4.3.6 После успешного входа пользователь попадает на страницу списка заданий.

2020-11-02 06:07 UTC, mihan007 requested changes
@romanrurenko Роман, проделана отличная работа. Остались сущие мелочи, доработай и я приму оперативно.

2020-11-02 06:07 UTC, mihan007 commented on frontend/controllers/LandingController.php
> +        var_dump($modelsTasks);
Убираем дебаг, когда посылаем PR

2020-11-02 06:07 UTC, mihan007 commented on frontend/models/File.php
> +            // flush the PHP output buffer to avoid overflowing the memory allocated for the script
Используй

```
return Yii::$app->response->sendFile($file);

2020-11-02 06:07 UTC, mihan007 commented on frontend/models/File.php
> +            // flush the PHP output buffer to avoid overflowing the memory allocated for the script
https://yiiframework.com.ua/ru/doc/guide/2/runtime-responses/#sending-files

2020-11-02 06:07 UTC, mihan007 commented on frontend/models/User.php
> +        if ($request['UsersFilterForm']['freeNow']) {
Оно упадет, если не будет $request['UsersFilterForm']['freeNow'], нужна проверка через isset, ее делали вместе, везде поправить

2020-11-02 06:07 UTC, mihan007 commented on frontend/models/User.php
> +        if ($request['UsersFilterForm']['feedbackExists']) {
Оно упадет, если в request не будет нужного фильтра

2020-11-02 06:07 UTC, mihan007 commented on frontend/models/User.php
> +        if ($request['UsersFilterForm']['isFavorite']) {
Оно упадет, если в request не будет нужного фильтра

2020-11-02 06:07 UTC, mihan007 commented on frontend/views/layouts/main.php
> +                        <a href="/task">Создать задание</a>
href создаем через методы Yii. Это позволит тебе изменять роуты в конфиге и они автоматически изменятся во view

https://www.yiiframework.com/doc/guide/2.0/en/runtime-routing#creating-urls

2020-11-02 06:07 UTC, mihan007 commented on frontend/views/task/create.php
> +$yandexApiJs = "https://api-maps.yandex.ru/2.1/?apikey=e666f398-c983-4bde-8f14-e3fec900592a&lang=ru_RU";
apikey вынести в конфиг приложения 

Yii::$app->params['yandex_api_key']

2020-11-02 06:07 UTC, mihan007 commented on frontend/views/tasks/index.php
> +//var_dump(Yii::$app->user->identity);
это мертвый код, его не должно быть в PR

2020-11-02 06:07 UTC, mihan007 commented on frontend/web/.htaccess
> +#RewriteCond %{REQUEST_URI} !^/(web)
Мертвый код убираем

2020-11-03 09:20 UTC, mihan007 commented
Для полировки до идеала рекомендую
1. https://github.com/htmlacademy-yii/603391-task-force-1/pull/19/files#diff-8eade2be20c3a02a8deac713aa39a3f1879fdaaf20486bf2678c68f6e9aa9c40R32 - вот тут 4 хардкодом, это нехорошо, так как это число может менять. называется magic numbers - антипаттерн. Такое лучше уносить в константу или в настройки приложения
2. https://github.com/htmlacademy-yii/603391-task-force-1/pull/19/files#diff-b1ac2439deafe4d459c5864d5538b9c64e326463e4d76535cede0eea5136da58R74 - мертвый код

2020-11-03 09:21 UTC, mihan007 approved these changes
Прекрасный результат, постарался знатно. Мелкие моменты в https://github.com/htmlacademy-yii/603391-task-force-1/pull/19#issuecomment-720997948, это можно сделать в последующих PR.

2020-11-03 09:21 UTC, merged