Add geocoder support to task pages
htmlacademy-yii/603391-task-force-1 pull request #21
Opened 2020-11-12 15:51 UTC by romanrurenko

2020-11-22 08:28 UTC, mihan007 requested changes
Роман, ты проделал очень большую работу. Мне было приятно изучить этот PR, очень радует когда студент показывает прекрасный результат. А ты показываешь.

Я оставил ряд комментариев, чтобы сделать код еще лучше. Там чутка по ошибкам и большинство связано с упрощением архитектуры и использованием всей мощи Yii2. Эти подсказки помогут тебе уже на этом первом проекте сделать реализацию, которую легко поддерживать и развивать. А эти два аспекта, пожалуй, самые важные. Жизнь проекта с момента релиза только начинается и если он сделан с использованием чистой и красивой архитектуры с соблюдением идеологии фреймворка, то это залог быстрого развития и любви бизнеса и разработчиков к продукту. 

Любить продукт бизнесмены будут потому что фичи будут быстро выходить, фичи выходят - больше пользователей приходят на сайт - бизнес больше зарабатывает на рекламе или продаже услуг на сайте - бизнес готов и дальше оплачивать работу программистов и развивать проект. 

Разработчики проект будут любить потому что он сделан в рамках идеологии фреймворка, сразу понятно где и что лежит и как реализовано.

Жду правок.

2020-11-22 08:28 UTC, mihan007 commented on frontend/controllers/MyListController.php
> +        $currentFilter = $filter;
переименуй входящий параметр в $currentFilter и эта строка будет не нужна. меньше ненужных строк - чище код - легче поддерживать и развивать

2020-11-22 08:28 UTC, mihan007 commented on frontend/controllers/ProfileController.php
> +
старайся не делать ненужных пустых строк. 1. неопрятно 2. кто-то из команды все равно их уберет и в последующем PR будет ненужный diff на этот файл, в котором убираются пустые строки. А так как ненужный, то кто-то зря потратит драгоценное время на его изучение. Вроде мелочь, но нет.

2020-11-22 08:28 UTC, mihan007 commented on frontend/controllers/SignupController.php
> +        $this->layout = 'signup';
скорее всего у тебя этот layout на все экшены этого контроллера? если так, то сделай layout в определении класс и тогда в рамках экшена не придется его указывать. 

да, сейчас у тебя тут один экшн и это кажется ненужным, но экшены скорее всегу будут добавляться и можно легко в них забыть указать верный layout

2020-11-22 08:28 UTC, mihan007 commented on frontend/controllers/TasksController.php
>      }
отлично, что удаляешь ненужные пустые строки. в конце файлов тоже посмотри, пожалуйста

2020-11-22 08:28 UTC, mihan007 commented on frontend/models/City.php
> +
не нужны тут пустые строки)

2020-11-22 08:28 UTC, mihan007 commented on frontend/models/Task.php
> +                    ['t.city_id' => Yii::$app->user->identity->city_id],
тут закралась ошибка. если пользователь не авторизован, то мы не можем получить его город. 

Я бы условие в этом andWhere вынес в отдельную переменную и заполнял бы ее в отдельной функции. В функции уже бы проверял авторизован пользователь или нет. Если авторизован, то отдавал бы условие, которое у тебя сейчас. Если нет, то только условие 't.city_id' => $currentCityId

2020-11-22 08:28 UTC, mihan007 commented on src/GeoCoder.php
> +        $response_data = json_decode($content, true);
Используй https://www.yiiframework.com/doc/api/2.0/yii-helpers-basejson#decode()-detail. Он выбрасывает yii\base\InvalidArgumentException и ты можешь как обычно поймать его в try .. catch и убрать $this->findJsonErrors. Сделал ты ее красиво, не спорю, но внутри фреймворка уже подобный функционал есть, давай его использовать

2020-11-22 08:28 UTC, mihan007 commented on frontend/models/Task.php
> +        $currentCityId = $session['current_city_id'];
не нашел в коде где ты записываешь в сессию эту переменную. 
1. подскажи в комментариях, пожалуйста.
2. есть подозрение, что в данном куске кода current_city_id может и не быть в сессии. может пользователь куки удалили или еще что - сессия очистилась. в этом случае логичнее всего попробовать узнать город пользователя по его IP. Можно это сделать через Яндекс.Локатор(https://yandex.ru/dev/locator/). Я бы для простоты и быстроты реализации использовал готовый пакет https://github.com/yandex-php/php-yandex-locator, возможно он работает - не тестил))

2020-11-22 08:28 UTC, mihan007 commented on frontend/views/layouts/main.php
> +$cities = City::getList();
не-не-не. так нельзя делать от слова совсем. не должна вьюха ходить в базу, никогда. либо из контроллера данные пришли, либо в виджете, либо еще как-то. но в хранилище она не ходит.

для случаев, когда тебе надо создать определенную часть страницы с сложной логикой и данными - это выносится в виджет. виджет может быть использован на странице сколько угодно раз (если нормально написан). 

вынеси все связанное с выбором города в виджет и здесь используй его https://www.yiiframework.com/doc/guide/2.0/en/structure-widgets (на русском https://yiiframework.com.ua/ru/doc/guide/2/structure-widgets/)

В виджете и будет вся логика работы с базой. И логика создания html кода на основе этой логики и данных из базы.

2020-11-22 08:28 UTC, mihan007 commented on frontend/views/layouts/main.php
>  $loggedUser = Yii::$app->user->identity;
Я бы вынес блок с аватаром и именем пользователя тоже в виджет, а в нем уже работал с Yii::$app->user->identity.

Да, для простоты можно Yii::$app->user->identity использовать во view, но я очень не рекомендую это делать. Просто представь, что у тебя view это простейшая функция, на вход которой попадают только определенные параметры. Эта функция ничего не знает, кроме этих параметров. Она не знает ни про Yii::$app, ни про модели, ни про что кроме входных параметров. Эти параметры она может использовать у себя при выводе, в циклах, в условиях, передавать в виджеты. Но она не должна никуда ходить. Не зря же слой view называют слой представления. Оно лишь показывает. Бизнес логику и общение с бд - это дело других слоев приложения.

2020-11-22 08:28 UTC, mihan007 commented on frontend/views/layouts/signup.php
> +<div class="table-layout">
подумай, кстати, в целом, чтобы отдельные общие части всех layout вынести в отдельные partial view или виджеты. сейчас у тебя 3 почти одинаковых layout и в них есть повторяющиеся блоки. Эти блоки надо вытащить из layout и переиспользовать их во всех layout. 

Для чего?
Высока вероятность, что эти блоки дизайнер будет менять и будет менять на всех страницах. Что ты будешь в этом случае делать? Сейчас - ты пойдешь в 3 layouts и будешь в каждом менять с высоким шансом ошибиться.

Что делать?
Для каждого блока надо понять будет ли partial view или виджет. Общее правило: 
- Если в блоке нет никаких обращений к сущностям Yii - к компонентам, базе - то делаем partial view, см https://github.com/samdark/yii2-cookbook/blob/master/book/reusing-views-via-partials.md
- Если есть - делаем виджет и инкапсулируем туда всю логику.
- Как только в partial view видем, что он распух и стал слишком много всего в себе делать, то делаем из него widget

Результат
1. Чище код
2. Легко изменять общие части всех страниц
3. Соблюдение принципа DRY, don't repeat yourself, https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself
4. Соблюдение принципа SRP из SOLID, смотри https://ru.wikipedia.org/wiki/SOLID_(%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BE%D1%80%D0%B8%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) и https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8. Каждый view и widget имеет строго свою задачу и работает в рамках нее

2020-11-22 08:28 UTC, mihan007 commented on frontend/views/my-list/index.php
> +                foreach (MyTask::FILTERS as $filter): ?>
фильтры так и просятся в partial view/widget

2020-11-22 08:28 UTC, mihan007 commented on frontend/views/site/error.php
> +$this->title = 'TaskForce - Ошибка';
задача со звездочкой. со звездочкой значит, что делать для принятия PR не обязательно. Это лишь пожелание, которое тебе может помочь в последующих проектах.

Я бы предложил работу с title сделать так. 
- создать трейт HasTitle
- в нем создать метод getTitle, который возвращает title страницы
- этот метод вызывать в layout и устанавливать его значение в $this->title
- в методе же title строить на основании названия класса контроллера и экшена

что это даст?
- легкое управление title в одном месте. если сеошники что-то новое придумают, то тебе не придется ходить по куче view и менять. Сходишь в один файл и поменяшь
- будет легко переводить title на другие языке
- да и в целом ты сможешь работу с title вообще вынести вне своего контроля. Сделать UI для их редактирования и отдать его админам сайта, пусть сами меняют как надо.

2020-11-22 08:28 UTC, mihan007 commented on frontend/views/task/create.php
> +$jsAjax = <<< AJAX
1. тут точно в виджет
2. ajax код уносим в отдельный .js файл - делаем чище view и позволяем браузеру его кэшировать, ускоряя следующую загрузку файла

2020-11-22 08:28 UTC, mihan007 commented on frontend/views/tasks/view.php
> +$apiKey = Yii::$app->params['yandex_api_key'];
в виджет

2020-11-22 08:28 UTC, mihan007 commented on src/Constant/MyTask.php
> +    const STATUS_BY_FILTER = [
на будущее посмотри на enum и его реализацию в php: https://github.com/spatie/enum. Этот пакет дает строгую типизацию для статусов в нашем случае и удобство работы с ними

2020-11-22 08:30 UTC, mihan007 commented
+ @romanrurenko посмотри трелло, там пару правок есть https://trello.com/b/wECeWeuj/%D1%80%D0%BE%D0%BC%D0%B0%D0%BD-%D1%80%D1%83%D1%80%D0%B5%D0%BD%D0%BA%D0%BE-task-force

2020-11-25 11:47 UTC, romanrurenko commented on frontend/models/Task.php
> +        $currentCityId = $session['current_city_id'];
Я сделаю как в задании указано, чтоб выбирался город из профиля, если нет в сессии. А локатор можно использовать чтоб предлагался текущий город при регистрации пользователя.

2020-12-01 09:36 UTC, mihan007 commented
1. Ошибка на главной, когда пользователь не авторизован. Скорее всего тут надо для данного кейса использовать default city, Москву например
![image](https://user-images.githubusercontent.com/939122/100721767-d3873600-33d0-11eb-93df-9b0f944e3d7f.png)
2. Ошибка, когда нет данных формы
![image](https://user-images.githubusercontent.com/939122/100722169-5c9e6d00-33d1-11eb-8a1d-0cdfed42f2cf.png)

Роман, мне кажется, что у тебя не включено отображение всех ошибок PHP. Это можно сделать через define('YII_DEBUG', true) и error_reporting=E_ALL в php.ini

Продолжу проверку, когда будут обработаны эти 2 ошибки и проверены на корректность работы остальные страницы. 
1. Когда я захожу на них - я не должен видеть ни одной ошибки. 
2. Проверить с авторизованным и неавторизованным пользователем.
3. С авторизованным пользователем проверить в обеих ролях - заказчик и исполнитель

2020-12-21 13:00 UTC, mihan007 approved these changes
- Замечаний к коду нет, отличная работа.
- По функционалу - не смог подгрузить фото работ. Детально протестирую уже в следующем PR.

2020-12-21 13:00 UTC, mihan007 commented on frontend/actions/AccountIndexAction.php
> +        {
два уровня вложенности, видимо опечатка

2020-12-21 13:00 UTC, mihan007 commented on frontend/controllers/AccountController.php
> +                'class' => 'frontend\actions\AccountIndexAction',
тут для работы автокомплита можно делать как AccountIndexAction::class

2020-12-21 13:02 UTC, mihan007 commented
- Отличная работа, принимаю!
На будущее:
- Не смог загрузить фото работы в профиле, посмотри попозже
![image](https://user-images.githubusercontent.com/939122/102779783-e1afed00-43a5-11eb-8b50-f5c1e9bd2de3.png)
- Посмотри в https://github.com/htmlacademy-yii/603391-task-force-1/pull/22 пару последних коммитов и в следующих задачах их поправь

2020-12-22 05:55 UTC, merged