Module8 task2
htmlacademy-yii/603391-task-force-1 pull request #23
Opened 2021-01-11 11:28 UTC by romanrurenko

2021-01-23 08:15 UTC, mihan007 requested changes
Привет! Хорошо получилось, отличная работа. Пройдись по замечаниям, пожалуйста. Из них не все надо править, где-то просто надо задуматься. Важно - разобрать замечания в API и вынесение из моделей функций уведомления.

2021-01-23 08:15 UTC, mihan007 commented on api/controllers/SiteController.php
> +class SiteController extends Controller
а нужен ли этот файл вообще? если хочешь просто папку оставить, то создай в ней файл с именем .gitsave

2021-01-23 08:15 UTC, mihan007 commented on api/modules/v1/controllers/MessagesController.php
> +            $actions['create'],
не уверен, что create надо удалять, если ты ниже его переопределяешь

2021-01-23 08:15 UTC, mihan007 commented on api/modules/v1/controllers/MessagesController.php
> +        $request = Yii::$app->request;
валидация входных данных для апи нужна точно также как и для обычных контроллеров

2021-01-23 08:15 UTC, mihan007 commented on api/modules/v1/controllers/TasksController.php
> +    public $modelClass = TaskList::class;
у тебя в соседнем классе был объявлен cors. почему в этом файле нет? скорее всего cors нужен во всех контроллерах поэтому надо сделать базовый класс ApiController, унаследовать его от ActiveController, объявить там cors и уже от этого класса остальные наследовать

2021-01-23 08:15 UTC, mihan007 commented on api/modules/v1/controllers/MessagesController.php
> +        if (!($userId === $task->executor_id || $userId === $task->customer_id)) {
https://www.yiiframework.com/doc/guide/2.0/en/rest-controllers#performing-access-check + наши наработки по правам доступа в веб приложении переиспользовать

2021-01-23 08:15 UTC, mihan007 commented on api/modules/v1/models/TaskList.php
> +                return Event::find()->where(
унести в модель или класс бизнес логики

2021-01-23 08:15 UTC, mihan007 commented on api/modules/v1/models/TaskList.php
> +                return User::findOne($this->customer_id)->name;
использовать relation у task, что-то вроде $this->customer->name

2021-01-23 08:15 UTC, mihan007 commented on frontend/actions/TaskCancelAction.php
> +            Event::createNotification($event);
эти Event и EventEntity конечно сводят слегка с ума)

2021-01-23 08:15 UTC, mihan007 commented on frontend/actions/TaskCancelAction.php
> +            Event::createNotification($event);
1. У тебя EventEntity по сути являются DTO, то есть назвав его EventDTO ты дашь понять читателю более точно его суть. Некритично вообще, важно чтобы ты это понимал.
2. Ты уже работаешь в рамках php 7.4, пора переезжать на 8.0. Переделай создание DTO на https://stitcher.io/blog/constructor-promotion-in-php-8 - получится по красоте

2021-01-23 08:15 UTC, mihan007 commented on frontend/actions/TaskCompleteAction.php
> +                    $event = new EventEntity(EventEntity::GROUP_TASK_ID);
https://stitcher.io/blog/constructor-promotion-in-php-8

2021-01-23 08:15 UTC, mihan007 commented on frontend/actions/TaskRefuseAction.php
> +            $event = new EventEntity(EventEntity::GROUP_TASK_ID);
https://stitcher.io/blog/constructor-promotion-in-php-8

2021-01-23 08:15 UTC, mihan007 commented on frontend/actions/TaskResponseAction.php
> +                $event = new EventEntity(EventEntity::GROUP_REVIEW_ID);
https://stitcher.io/blog/constructor-promotion-in-php-8

2021-01-23 08:15 UTC, mihan007 commented on frontend/controllers/EventsController.php
> +        if (!$userId = Yii::$app->user->getId()) {
что-то я вообще не понял откуда здесь $userId и в целом условие странное. вроде бы должно быть $user != .... Ошибку еще надо выкидывать, если это 403

2021-01-23 08:15 UTC, mihan007 commented on frontend/controllers/EventsController.php
> +        Event::updateAll(['viewed' => 1], "user_id=$userId");
второй параметр лучше записать как ['=', 'user_id', $userId]

2021-01-23 08:15 UTC, mihan007 commented on frontend/models/forms/CategoriesFilterForm.php
>              if ((bool)$value) {
1. можно инвертировать условие и не будет увеличение вложенности.
2. кастовать к bool тут необязательно, php сам это делает внутри условий

я бы записал как.
if (!$value) {
  continue;
}
а после этого уже обычный код, который у тебя тут

2021-01-23 08:15 UTC, mihan007 commented on frontend/models/Chat.php
> +        return $this->hasOne(User::class, ['id' => 'user_id']);
в phpdoc * @property User $customer

может тут надо переделать на getCustomer?

2021-01-23 08:15 UTC, mihan007 commented on frontend/models/Event.php
> +    public static function findEvents(int $userId): array
попробуй поменять название функции на более точное, чтобы было понятно, что она делает. Например, findEventsForUser

2021-01-23 08:15 UTC, mihan007 commented on frontend/models/Event.php
> +        Yii::$app->mailer->compose()
ох не стал бы я нотификации в модели делать. модель она же для абстракции бд через ооп. предлагаю унести нотификации в отдельный сервис. 

У тебя получится что-то вроде
EventNotificationService::sendEmail(Event $event) и внутри него уже всю логику утащишь.

2021-01-23 08:15 UTC, mihan007 commented on frontend/models/Event.php
> +        $addressee = User::findOrFail((int)$event->user_id, 'User not found');
Можешь быть получить адресата просто через $event->user?

2021-01-23 08:15 UTC, mihan007 commented on frontend/models/User.php
> +        $profileId = (int)Profile::findByUserId($userId)['profile_id'];
1. Обычно я делаю так, чтобы модель текущего пользователя была доступна через Yii::$app->user->model. Тогда профайл можно получить через Yii::$app->user->model->profile. 

2. Или вообще написать хелперы-функции, где

- current_user() вернет модель текущего пользователя
- current_profile() вернет профиль текущего пользователя

будет что-то вроде
function current_user()
{
  return Yii::$app->user->model
}

3. Еще варианты сделать это через User::current() и Profile::current()

Ключевая мысль тут - эти сущности тебе очень часто нужны по коду и лучше их один раз красиво написать и везде использовать. И нагляднее будет, и проще писать и понимать.

2021-01-23 08:15 UTC, mihan007 commented on src/EventEntity.php
> +class EventEntity
стоит подумать. этот класс у тебя похож на Dto, а вот TaskEntity уже похож на сущность бизнес логики. Пусть и этот тогда останется Entity

2021-01-23 08:15 UTC, mihan007 commented on src/TaskEntity.php
> +    public function getOwnerUserId(): int
из названия функции не очень понятно почему в одном случае id заказчика, а в другом исполнителя. я бы переименовал

2021-01-24 09:35 UTC, romanrurenko commented on api/modules/v1/controllers/MessagesController.php
> +            $actions['create'],
проверил, еще раз, надо удалять.

2021-03-11 15:37 UTC, mihan007 commented on frontend/actions/TaskCancelAction.php
> +            Event::createNotification($event);
```
class EventEntity
{
    public function __construct(
        public string $user_id, 
        public string $task_id, 
        public string $info,
    ) {}
}

$event = new EventEntity(
    user_id: $task->getAssistUserId(),
    task_id: $id,
    info: self::TASK_CANCELED
);

```

2021-03-29 06:53 UTC, merged